- name: php installations
  hosts: all
  become: yes
  tasks:
    
    - name: install apache on ubuntu
      ansible.builtin.apt:
        name: "{{ package }}"
        state: present
        update_cache: true
    
    - name: install php service
      apt: 
        name: "{{ php_packages }}"
        state: present
        update_cache: true
    - name: copy the file
      copy: 
        src: info.php
        dest: /var/www/html/info.php
    - name: restart apache
      service:
        name: apache2
        state: restarted 